USE [master]
GO

/****** Object:  Database [UserData]    Script Date: 10-04-2024 14:40:09 ******/
CREATE DATABASE [UserData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserData] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserData] SET  MULTI_USER 
GO

ALTER DATABASE [UserData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UserData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UserData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UserData] SET  READ_WRITE 
GO

